---
#
# Ansible managed
#
repository:
  description: Install cron and scedule jobs on your system.
  homepage: https://robertdebock.nl/
  topics: cron, crontab, scheduling, system, ansible, molecule, tox, playbook
